# Generated by Django 5.2.4 on 2025-07-24 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='メール通知')),
                ('daily_report', models.BooleanField(default=False, verbose_name='日次レポート')),
                ('weekly_report', models.BooleanField(default=True, verbose_name='週次レポート')),
                ('records_per_page', models.IntegerField(default=20, verbose_name='1ページあたりの表示件数')),
                ('default_period_days', models.IntegerField(default=7, verbose_name='デフォルト表示期間（日）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('teacher', models.OneToOneField(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='講師')),
            ],
            options={
                'verbose_name': '講師ダッシュボード設定',
                'verbose_name_plural': '講師ダッシュボード設定',
            },
        ),
    ]
