# Generated by Django 4.2.7 on 2025-07-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('1年生', '1'), ('2年生', '2'), ('3年生', '3'), ('4年生', '4'), ('5年生', '5'), ('6年生', '6'), ('その他', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
