# Generated by Django 4.2.7 on 2025-07-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age_customuser_grade_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('1', '1年生'), ('2', '2年生'), ('3', '3年生'), ('4', '4年生'), ('5', '5年生'), ('6', '6年生'), ('Other', 'その他')], default='Other', max_length=10),
        ),
    ]
