# Generated by Django 4.2.7 on 2025-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_store_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='account_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
        migrations.AddField(
            model_name='item',
            name='dealer',
            field=models.ManyToManyField(to='accounts.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='items',
            field=models.ManyToManyField(to='accounts.item'),
        ),
    ]
