# Generated by Django 4.2.7 on 2025-07-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='招待コード')),
                ('name', models.CharField(max_length=50, verbose_name='招待者名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('used_count', models.IntegerField(default=0, verbose_name='使用回数')),
            ],
            options={
                'verbose_name': '招待コード',
                'verbose_name_plural': '招待コード',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='invitation_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.invitationcode', verbose_name='使用した招待コード'),
        ),
    ]
