# Generated by Django 4.2.7 on 2025-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invitationcode_customuser_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
    ]
