# Generated by Django 4.2.7 on 2025-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_invitationcode_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grade',
        ),
        migrations.AddField(
            model_name='customuser',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='入学年度'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('computer_science', 'コンピュータサイエンス学科'), ('information_technology', '情報技術学科'), ('software_engineering', 'ソフトウェア工学科'), ('data_science', 'データサイエンス学科'), ('cybersecurity', 'サイバーセキュリティ学科'), ('other', 'その他')], default='other', max_length=30, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名前'),
        ),
    ]
