# Generated by Django 4.2.7 on 2025-07-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_age_remove_customuser_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='type',
            field=models.CharField(choices=[('student', '生徒用'), ('teacher', '講師用')], default='student', max_length=10, verbose_name='種別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('student', '生徒'), ('teacher', '講師')], default='student', max_length=10, verbose_name='アカウント種別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('IT_highclass_sougou', 'ITハイクラス総合'), ('IT_sougou', 'IT総合'), ('AI_IOT_senkou', 'AI/IOT専攻'), ('whitehacker_senkou', 'ホワイトハッカー専攻'), ('teacher', '講師'), ('other', 'その他')], default='other', max_length=30, verbose_name='学科'),
        ),
    ]
