# Generated by Django 4.2.7 on 2025-07-23 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_invitationcode_type_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('student', '生徒'), ('teacher', '講師'), ('kiosk', 'キオスク')], default='student', max_length=10, verbose_name='アカウント種別'),
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='キオスク名')),
                ('location', models.CharField(max_length=100, verbose_name='設置場所')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(limit_choices_to={'type': 'kiosk'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='キオスクユーザー')),
            ],
            options={
                'verbose_name': 'キオスク',
                'verbose_name_plural': 'キオスク',
                'ordering': ['-created_at'],
            },
        ),
    ]
