# Generated by Django 5.2.4 on 2025-07-23 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_type_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_teacher', to=settings.AUTH_USER_MODEL, verbose_name='担当講師'),
        ),
    ]
