# Generated by Django 4.2.7 on 2025-08-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teacher_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
    ]
