# Generated by Django 4.2.7 on 2025-08-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_customuser_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type',
        ),
        migrations.DeleteModel(
            name='Kiosk',
        ),
    ]
