# Generated by Django 4.2.7 on 2025-08-27 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_customuser_type_delete_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='授業日時'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(limit_choices_to={'invitation_code__type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
