# Generated by Django 4.2.7 on 2025-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_lesson_lesson_date_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('student', '生徒'), ('teacher', '講師'), ('kiosk', 'キオスク')], default='student', max_length=10, verbose_name='アカウント種別'),
        ),
    ]
