# Generated by Django 4.2.7 on 2025-08-28 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='アクティブ'),
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='場所')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_kiosks', to='accounts.lesson', verbose_name='現在のレッスン')),
                ('user', models.OneToOneField(limit_choices_to={'type': 'kiosk'}, on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
