# Generated by Django 4.2.7 on 2025-08-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_lesson_is_active_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='現在のセッションキー'),
        ),
    ]
