# Generated by Django 4.2.7 on 2025-08-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_current_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', '1年'), ('2', '2年'), ('3', '3年')], max_length=1, null=True, verbose_name='学年'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, choices=[('system_engineer', 'システムエンジニア専攻'), ('web_engineer', 'WEBエンジニア専攻')], max_length=20, null=True, verbose_name='専攻'),
        ),
    ]
