# Generated by Django 4.2.7 on 2025-08-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_grade_alter_customuser_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='target_grade',
            field=models.CharField(blank=True, choices=[('1', '1年'), ('2', '2年'), ('3', '3年')], default='', max_length=1, verbose_name='対象学年'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='target_major',
            field=models.CharField(blank=True, choices=[('SE', 'システムエンジニア専攻'), ('WEB', 'WEBエンジニア専攻')], default='', max_length=20, verbose_name='対象専攻'),
        ),
    ]
