# Generated by Django 5.2.4 on 2025-07-23 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_token', '0002_attendancetoken_delete_qr_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancetoken',
            options={'ordering': ['-created'], 'verbose_name': '出席確認トークン', 'verbose_name_plural': '出席確認トークン'},
        ),
        migrations.AlterField(
            model_name='attendancetoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='attendancetoken',
            name='expires',
            field=models.DateTimeField(verbose_name='有効期限'),
        ),
        migrations.AlterField(
            model_name='attendancetoken',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='使用済みフラグ'),
        ),
        migrations.AlterField(
            model_name='attendancetoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='出席確認トークン'),
        ),
        migrations.AlterField(
            model_name='attendancetoken',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='attendancetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_tokens', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(auto_now_add=True, verbose_name='出席確認日時')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='出席場所')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance_token.attendancetoken', verbose_name='使用トークン')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '出席記録',
                'verbose_name_plural': '出席記録',
                'ordering': ['-attended_at'],
                'unique_together': {('user', 'token')},
            },
        ),
    ]
