# Generated by Django 4.2.7 on 2025-07-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_type_kiosk'),
        ('attendance_token', '0003_alter_attendancetoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='kiosk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.kiosk', verbose_name='読み取りキオスク'),
        ),
    ]
