# Generated by Django 4.2.7 on 2025-08-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_token', '0004_attendancerecord_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', '出席'), ('late', '遅刻')], default='present', max_length=10, verbose_name='出席状態'),
        ),
    ]
