# Generated by Django 4.2.7 on 2025-08-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_token', '0005_attendancerecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='kiosk',
        ),
    ]
