# Generated by Django 4.2.7 on 2025-08-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_token', '0006_remove_attendancerecord_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetoken',
            name='issued_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='発行元IPアドレス'),
        ),
    ]
