# Generated by Django 4.2.7 on 2025-08-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_lesson_is_active_kiosk'),
        ('attendance_token', '0007_attendancetoken_issued_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='accounts.lesson', verbose_name='レッスン'),
        ),
    ]
