# Generated by Django 4.2.7 on 2025-08-30 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_lesson_is_active_kiosk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance_token', '0008_attendancerecord_end_time_attendancerecord_lesson'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('user', 'lesson')},
        ),
    ]
